SET IDENTITY_INSERT [dbo].[LmsActivity] ON
INSERT INTO [dbo].[LmsActivity] ([Id], [Name], [Description], [StartDate], [EndTime], [LmsActivityTypeId], [ModuleId]) VALUES (1, N'C# Fundamentals with Visual Studio 2017', N'Instalera och Lär dig VC', N'2019-03-04 00:00:00', N'2019-03-06 00:00:00', 1, 1)
INSERT INTO [dbo].[LmsActivity] ([Id], [Name], [Description], [StartDate], [EndTime], [LmsActivityTypeId], [ModuleId]) VALUES (2, N'C# Fundamentals with C# 5.0', N'C# Fundamentals with C# 5.0 is designed to give you everything you need to become a productive C# developer on the .NET platform.', N'2019-03-05 00:00:00', N'2019-03-05 00:00:00', 1, 1)
INSERT INTO [dbo].[LmsActivity] ([Id], [Name], [Description], [StartDate], [EndTime], [LmsActivityTypeId], [ModuleId]) VALUES (3, N'C# Best Practices: Improving on the Basics', N'This course covers best practices for using basic C# features, guiding you on the path from apprentice to skilled C# software developer.', N'2019-03-05 00:00:00', N'2019-03-05 00:00:00', 1, 1)
INSERT INTO [dbo].[LmsActivity] ([Id], [Name], [Description], [StartDate], [EndTime], [LmsActivityTypeId], [ModuleId]) VALUES (4, N'C# Fundamentals with C# 5.0', N'C# Fundamentals with C# 5.0 is designed to give you everything you need to become a productive C# developer on the .NET platform.', N'2019-03-06 00:00:00', N'2019-03-06 00:00:00', 1, 1)
INSERT INTO [dbo].[LmsActivity] ([Id], [Name], [Description], [StartDate], [EndTime], [LmsActivityTypeId], [ModuleId]) VALUES (5, N'C# Fundamentals with C# 5.0', N'C# Fundamentals with C# 5.0 is designed to give you everything you need to become a productive C# developer on the .NET platform.', N'2019-03-06 00:00:00', N'2019-03-06 00:00:00', 1, 1)
INSERT INTO [dbo].[LmsActivity] ([Id], [Name], [Description], [StartDate], [EndTime], [LmsActivityTypeId], [ModuleId]) VALUES (6, N'C# Best Practices: Improving on the Basics', N'This course covers best practices for using basic C# features, guiding you on the path from apprentice to skilled C# software developer.', N'2019-03-05 00:00:00', N'2019-03-05 00:00:00', 1, 1)
INSERT INTO [dbo].[LmsActivity] ([Id], [Name], [Description], [StartDate], [EndTime], [LmsActivityTypeId], [ModuleId]) VALUES (7, N'C# Fundamentals with C# 5.0', N'C# Fundamentals with C# 5.0 is designed to give you everything you need to become a productive C# developer on the .NET platform.', N'2019-03-07 00:00:00', N'2019-03-07 00:00:00', 1, 1)
INSERT INTO [dbo].[LmsActivity] ([Id], [Name], [Description], [StartDate], [EndTime], [LmsActivityTypeId], [ModuleId]) VALUES (8, N'C# Fundamentals with C# 5.0', N'C# Fundamentals with C# 5.0 is designed to give you everything you need to become a productive C# developer on the .NET platform.', N'2019-03-08 00:00:00', N'2019-03-08 00:00:00', 1, 1)
INSERT INTO [dbo].[LmsActivity] ([Id], [Name], [Description], [StartDate], [EndTime], [LmsActivityTypeId], [ModuleId]) VALUES (9, N'Java Setup', N'Java and Eclipse', N'2019-03-06 00:00:00', N'2019-03-08 00:00:00', 3, 3)
SET IDENTITY_INSERT [dbo].[LmsActivity] OFF
