SET IDENTITY_INSERT [dbo].[Document] ON
INSERT INTO [dbo].[Document] ([Id], [Name], [Description], [TimeStamp], [Url], [PersonId], [UserName], [CourseId], [LmsActivityId], [ModuleId]) VALUES (1, N'building-your-first-aspnet-core-application-slides.pdf', N'PDF', N'2019-03-04 14:33:22', N'\Documents\building-your-first-aspnet-core-application-slides.pdf', NULL, NULL, NULL, 1, 1)
INSERT INTO [dbo].[Document] ([Id], [Name], [Description], [TimeStamp], [Url], [PersonId], [UserName], [CourseId], [LmsActivityId], [ModuleId]) VALUES (2, N'building-your-first-aspnet-core-application-slides.pdf', N'PDF', N'2019-03-04 14:33:58', N'\Documents\building-your-first-aspnet-core-application-slides.pdf', NULL, NULL, NULL, 2, 1)
INSERT INTO [dbo].[Document] ([Id], [Name], [Description], [TimeStamp], [Url], [PersonId], [UserName], [CourseId], [LmsActivityId], [ModuleId]) VALUES (3, N'startup-and-middleware-slides.pdf', N'PDF', N'2019-03-04 14:34:12', N'\Documents\startup-and-middleware-slides.pdf', NULL, NULL, NULL, 2, 1)
INSERT INTO [dbo].[Document] ([Id], [Name], [Description], [TimeStamp], [Url], [PersonId], [UserName], [CourseId], [LmsActivityId], [ModuleId]) VALUES (4, N'controllers-in-the-mvc-framework-slides.pdf', N'PDF', N'2019-03-04 14:34:22', N'\Documents\controllers-in-the-mvc-framework-slides.pdf', NULL, NULL, NULL, 3, 1)
INSERT INTO [dbo].[Document] ([Id], [Name], [Description], [TimeStamp], [Url], [PersonId], [UserName], [CourseId], [LmsActivityId], [ModuleId]) VALUES (12, N'models-in-the-mvc-framework-slides.pdf', N'PDF', N'2019-03-04 15:02:37', N'C:\Users\Tommy\source\repos\MMTP-LMS\MMTP-LMS\wwwroot\Documents\models-in-the-mvc-framework-slides.pdf', NULL, N'Tom@Tom.se', NULL, NULL, NULL)
INSERT INTO [dbo].[Document] ([Id], [Name], [Description], [TimeStamp], [Url], [PersonId], [UserName], [CourseId], [LmsActivityId], [ModuleId]) VALUES (13, N'using-the-entity-framework-slides.pdf', NULL, N'2019-03-04 15:20:33', N'C:\Users\Tommy\source\repos\MMTP-LMS\MMTP-LMS\wwwroot\Documents\using-the-entity-framework-slides.pdf', NULL, N'Tom@Tom.se', NULL, NULL, NULL)
INSERT INTO [dbo].[Document] ([Id], [Name], [Description], [TimeStamp], [Url], [PersonId], [UserName], [CourseId], [LmsActivityId], [ModuleId]) VALUES (14, N'hello.cs', NULL, N'2019-03-04 15:32:28', N'C:\Users\Tommy\source\repos\MMTP-LMS\MMTP-LMS\wwwroot\Documents\hello.cs', NULL, N'Mmtp@Lexicon.se', NULL, NULL, NULL)
INSERT INTO [dbo].[Document] ([Id], [Name], [Description], [TimeStamp], [Url], [PersonId], [UserName], [CourseId], [LmsActivityId], [ModuleId]) VALUES (15, N'aspnet-identity-slides.pdf', NULL, N'2019-03-05 10:39:02', N'C:\Users\Tommy\source\repos\MMTP-LMS\MMTP-LMS\wwwroot\Documents\aspnet-identity-slides.pdf', NULL, N'student@skola.se', NULL, NULL, NULL)
INSERT INTO [dbo].[Document] ([Id], [Name], [Description], [TimeStamp], [Url], [PersonId], [UserName], [CourseId], [LmsActivityId], [ModuleId]) VALUES (16, N'front-end-frameworks-and-tools-slides.pdf', N'Övning 4 svar', N'2019-03-05 10:40:20', N'C:\Users\Tommy\source\repos\MMTP-LMS\MMTP-LMS\wwwroot\Documents\front-end-frameworks-and-tools-slides.pdf', NULL, N'student@skola.se', NULL, NULL, NULL)
INSERT INTO [dbo].[Document] ([Id], [Name], [Description], [TimeStamp], [Url], [PersonId], [UserName], [CourseId], [LmsActivityId], [ModuleId]) VALUES (17, N'aspnet-identity-slides.pdf', N'Test', N'2019-03-07 09:20:00', N'C:\Users\Tommy\source\repos\MMTP-LMS\MMTP-LMS\wwwroot\Documents\aspnet-identity-slides.pdf', NULL, N'Mmtp@Lexicon.se', NULL, NULL, NULL)
INSERT INTO [dbo].[Document] ([Id], [Name], [Description], [TimeStamp], [Url], [PersonId], [UserName], [CourseId], [LmsActivityId], [ModuleId]) VALUES (18, N'Roasted_coffee_beans_dark.jpg', NULL, N'2019-03-07 10:38:53', N'C:\Users\Tommy\source\repos\MMTP-LMS\MMTP-LMS\wwwroot\Documents\Roasted_coffee_beans_dark.jpg', N'adf2053b-e9f6-48e0-99ea-695362252ffc', N'Mmtp@Lexicon.se', NULL, NULL, NULL)
SET IDENTITY_INSERT [dbo].[Document] OFF
